### ISSUE TITLE
Recognize hidden FAT partition (0x1c) as a valid boot

### ISSUE THREAD

**Issue by tianyuanhao** [raspberrypi/rpi-eeprom#313]
**Mandatory information**
* *Raspberry Pi 4 Model B Rev 1.2*

**Describe the bug**
Cannot boot from hidden FAT partition (0x1c).

**To Reproduce**
Just power on the machine.

**Expected behaviour**
Can boot from hidden FAT partition (0x1c).

**Bootloader version and configuration**
`vcgencmd` is not available.

**SD card boot (please complete the following information):**
 - Partition information (sudo fdisk -l) if you are able to obtain this from another computer.
```
Device      Boot  Start    End Sectors  Size Id Type
sdcard.img1        2048 264191  262144  128M 1c Hidden W95 FAT32 (LBA)
```

**Comment by timg236** [comment]
Please can you explain why this is useful? AFAIK Raspberry PI has never supported this

**Comment by tianyuanhao** [comment]
This is only used to prevent the partition from being automatically mounted on Windows or Linux. It is no different from a normal FAT partition (0xc), I think it is very simple to support it. If it is really difficult, I will use the EFI partition (0xef) instead.

**Comment by timg236** [comment]
The ROM won't recognize this so recovery.bin won't work and I suspect that start.elf won't recognize this partition id either.

**Comment by tianyuanhao** [comment]
@timg236 Did you mean `0xc` or `0xef`? Currently I am using `0xef` and it works. In fact, this issue is a feature request.

**Comment by tianyuanhao** [comment]
If you think this feature is really not worth implementing, I will close it.

**Comment by timg236** [comment]
I meant 0x1c.

Please leave the issue open and add any relevant detail about hiding the boot partition from Windows. It's useful to have this information there in-case there is a broader requirement here. I can't commit to implementing this feature or not but if it is then this issue will get updated.
Unfortunately, features that also require start.elf to be updated take a long time to become available becuase start.elf then has to be updated in rpi-update, apt, Raspberry Pi OS and other distros. The rpi-update to APT stage is necessarily slow because it depends all the other FW changes.

**Comment by timg236** [comment]
Closed due to inactivity
