### ISSUE TITLE
[tryboot] issues booting with EEPROM update on A/B boot partitions

### ISSUE THREAD

**Issue by koehlma** [raspberrypi/rpi-eeprom#499]
### Describe the bug

The Raspberry Pi refuses to boot and the green LED keeps flashing fast. The issue seems to be caused when an EEPROM update (or configuration update) is placed on an A/B boot partition in combination with an `autoboot.txt` on the first partition.

Note that this may happen because we mount the respective A/B boot partitions to `/boot`.

### Steps to reproduce the behaviour

Use a partition layout as suggested by the [example update flow for A/B booting](https://www.raspberrypi.com/documentation/computers/config_txt.html#example-update-flow-for-ab-booting):

```
P1: boot (FAT32)
P2: boot-a (FAT32)
P3: boot-b (FAT32)
P4: extended
P5: system-a (ext4)
P6: system-b (ext4)
```

Use the following `autoboot.txt` (again as suggested) and place it on the first partition (`boot`):
```
[all]
tryboot_a_b=1
boot_partition=2
[tryboot]
boot_partition=3
```

Now, place an EEPROM update (`pieeprom.upd`, `pieeprom.sig`, and `recovery.bin`) on the second partition (`boot-a`).

### Device (s)

Raspberry Pi 4 Mod. B

### Bootloader configuration.

```
# rpi-eeprom-config pieeprom.upd
[all]
BOOT_UART=1
WAKE_ON_GPIO=1
POWER_OFF_ON_HALT=0
```

### System

```
# vcgencmd bootloader_version
2023/05/11 07:26:03
version 4fd8f1f3f7a05f7756edb1d3f15ffd7e428981f5 (release)
timestamp 1683786363
update-time 1701129143
capabilities 0x0000007f
```

```
# vcgencmd version
Aug 10 2023 15:33:38
Copyright (c) 2012 Broadcom
version 03dc77429335caee083e22ddc8eec09c07f12a7a (clean) (release) (start)
```

```
# fdisk -l
Device         Boot    Start      End  Sectors  Size Id Type
/dev/mmcblk0p1          8192   532479   524288  256M  c W95 FAT32 (LBA)
/dev/mmcblk0p2        532480   794623   262144  128M  c W95 FAT32 (LBA)
/dev/mmcblk0p3        794624  1056767   262144  128M  c W95 FAT32 (LBA)
/dev/mmcblk0p4       1056768 62357503 61300736 29.2G  5 Extended
/dev/mmcblk0p5       1064960  9453567  8388608    4G 83 Linux
/dev/mmcblk0p6       9461760 17850367  8388608    4G 83 Linux
/dev/mmcblk0p7      17858560 62357503 44498944 21.2G 83 Linux
```

**Comment by timg236** [comment]
"Now, place an EEPROM update (pieeprom.upd, pieeprom.sig, and recovery.bin) on the second partition (boot-a)."

Unfortunately, recovery.bin must be placed on the primary partition P1 and not boot-a or boot-b. recovery.bin doesn't know where it was loaded from by the bootrom and therefore can't delete itself.

Alternatives
1. Install recovery.bin pieeprom.bin and pieeprom.sig to the primary boot partition
2. Use partition a/b but self-update - just install pieeprom.upd pieeprom.sig no recovery.bin
3. Use flashrom instead of recovery.bin - recent change so a bit beta right now

Using flashrom to update from the OS will become the default for Pi5. It may also be more convenient on Pi4 so long as analog audio is not used due to GPIO pin sharing/conflicts

Latest rpi-eeeprom add RPI_EEPROM_USE_FLASHROM=1 to /etc/default/rpi-eeprom-update
https://github.com/raspberrypi/rpi-eeprom/commit/db154d47102a735a8214080e42c67871db93a8e7

**Comment by koehlma** [comment]
Thanks for the quick response!

Yes, that makes perfect sense. However, I wonder why the firmware tries to load it in the first place. I guess, this cannot be changed as it is done by the burned-in firmware?

**Comment by timg236** [comment]
> Thanks for the quick response!
> 
> Yes, that makes perfect sense. However, I wonder why the firmware tries to load it in the first place. I guess, this cannot be changed as it is done by the burned-in firmware?

It's the bootrom not the firmware.
